// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Customer struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Email       string `json:"email"`
	Phonenumber string `json:"phonenumber"`
	Password    string `json:"password"`
}

type ItemInput struct {
	ProductID int `json:"product_id"`
	Quantity  int `json:"quantity"`
}

type Order struct {
	ID              int          `json:"id"`
	Customer        *Customer    `json:"customer"`
	CustomerID      int          `json:"customer_id"`
	Item            []*OrderItem `json:"item"`
	TotalPrice      float64      `json:"totalPrice"`
	DateOrderPlaced time.Time    `json:"date_order_placed"`
}

type OrderItem struct {
	ID        int      `json:"id"`
	Order     *Order   `json:"order"`
	Product   *Product `json:"product"`
	ProductID int      `json:"product_id"`
	Quantity  int      `json:"quantity"`
	OrderID   int      `json:"-" gorm:"constraint:OnUpdate:CASCADE,OnDelete:SET NULL;"`
}

type Product struct {
	ID    int     `json:"id"`
	Name  string  `json:"name"`
	Price float64 `json:"Price"`
}

type CustomerInput struct {
	Name        string `json:"name"`
	Email       string `json:"email"`
	Phonenumber string `json:"phonenumber"`
	Password    string `json:"password"`
}

type LoginDetails struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type OrderInput struct {
	CustomerID int          `json:"customer_id"`
	Item       []*ItemInput `json:"item"`
	Price      float64      `json:"price"`
}

type ProductInput struct {
	Name  string  `json:"name"`
	Price float64 `json:"price"`
}
