// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Customer struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Phonenumber string `json:"Phonenumber"`
	Email       string `json:"Email"`
}

type Item struct {
	ID       int    `json:"id"`
	Name     string `json:"name"`
	Quantity int    `json:"quantity"`
	OrderID  int    `json:"-"`
}

type ItemInput struct {
	Name     string `json:"name"`
	Quantity int    `json:"quantity"`
}

type Order struct {
	ID              int       `json:"id"`
	Customer        *Customer `json:"customer"`
	CustomerID      int       `json:"customer_id"`
	Item            []*Item   `json:"item"`
	Price           float64   `json:"price"`
	DateOrderPlaced time.Time `json:"date_order_placed"`
}

type User struct {
	ID       int    `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type CreatedUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type CustomerInput struct {
	Name        string `json:"name"`
	Phonenumber string `json:"Phonenumber"`
	Email       string `json:"Email"`
}

type LoginDetails struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type OrderInput struct {
	CustomerID      int          `json:"customer_id"`
	Item            []*ItemInput `json:"item"`
	Price           float64      `json:"price"`
	DateOrderPlaced time.Time    `json:"date_order_placed"`
}
