// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Customer struct {
	ID          int      `json:"id"`
	Name        string   `json:"name"`
	Phonenumber int      `json:"Phonenumber"`
	Email       string   `json:"Email"`
	Orders      []*Order `json:"orders"`
}

type Item struct {
	ID       int    `json:"id"`
	Name     string `json:"name"`
	Quantity int    `json:"quantity"`
	OrderID  int    `json:"-"`
}

type ItemInput struct {
	Name     string `json:"name"`
	Quantity int    `json:"quantity"`
}

type Order struct {
	ID              int       `json:"id"`
	Item            []*Item   `json:"item"`
	Price           float64   `json:"price"`
	DateOrderPlaced time.Time `json:"date_order_placed"`
	CustomerID      int       `json:"-"`
}

type CustomerInput struct {
	Name        string        `json:"name"`
	Phonenumber int           `json:"Phonenumber"`
	Email       string        `json:"Email"`
	Orders      []*OrderInput `json:"orders"`
}

type OrderInput struct {
	Item            []*ItemInput `json:"item"`
	Price           float64      `json:"price"`
	DateOrderPlaced time.Time    `json:"date_order_placed"`
}
